services:

  postgres:
    image: postgres:16-alpine

    container_name: devops-assessment-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: hotel_booking
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

      - ./migrations:/docker-entrypoint-initdb.d/01-migrations:ro
      - ./seeds:/docker-entrypoint-initdb.d/02-seeds:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d hotel_booking"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
